### ISSUE TITLE
Requirements Engineering Prozess (Prozess und Dokumentation aller gefundenen Requirements. Fokus sollte hierbei auf den User Requirements liegen)

### ISSUE THREAD

**Issue by NerdyStuff** [Grimmig18/se2#6]
Durchgeführter Requirements Engineering Prozess und Dokumentation aller Requirements

**Comment by NerdyStuff** [comment]
Durchgeführter Requirements Engineering Prozess und Dokumentation aller gefundenen Requirements. Fokus sollte hierbei auf den User Requirements liegen

**Comment by Tony1704** [comment]
https://docs.google.com/document/d/1vWOxPXb1_RnlpwzobRerj6bH13YSyatZyklG-iHjS9Y/edit#
https://docs.google.com/spreadsheets/d/1q3PKMh9S7NPrCmNM-szBEXrIZ_cRcq3tfro_mnubOF8/edit#gid=0
fertig
